### ISSUE TITLE
Should RACK_ENV be respected in production?

### ISSUE THREAD

**Issue by andrewcroome** [icelab/snowflakes#2]
Hi @solnic. I've noticed that running `./bin/run db migrate` on heroku where RACK_ENV is `production` still attempts to dump the schema, resulting in a prompt for the database password.

Is it right that `RACK_ENV=production` should mean that snowflakes assumes it's in production, or is there another intention? @timriley has noticed recently in test that he needs to pass `-e test` rather than RACK_ENV=test. 

Some discussion here: https://icelab.slack.com/archives/C2BT34RK7/p1518490460000199

Thanks!

**Comment by solnic** [comment]
@andrewcroome this is not good, sorry about that. Snowflakes should respect whatever the application sets as its env, I need to make sure that this is what happens. I'll deal with it.

**Comment by solnic** [comment]
This is fixed in master
